#ALUMNO: JONATAN TAJADA RICO

#DROP database if exists gestionVentasEntradas ;

create database if not exists gestionVentasEntradas collate utf8mb4_spanish2_ci;
use gestionVentasEntradas;



CREATE TABLE RECINTOS (

    COD_RECINTO INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CIUDAD VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    HORARIO VARCHAR(255) NOT NULL
);


CREATE TABLE ESPECTACULOS (

    COD_ESPECTACULO INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255),
    FECHA_INICIAL DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    INTERPRETE VARCHAR(255),
    COD_RECINTO INT NOT NULL,
		CONSTRAINT FK_COD_RECINTO FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE PRECIOS_ESPECTACULOS (

    COD_ESPECTACULO INT,
    COD_RECINTO INT,
    ZONA VARCHAR(255),
    PRECIO DECIMAL(10, 2),
    
		PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO, ZONA),
		CONSTRAINT FK_COD_ESPECTACULO FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO) ON UPDATE CASCADE ON DELETE CASCADE,
		CONSTRAINT FK_COD_RECINTO_PRECIOS_ESPECTACULOS FOREIGN KEY (COD_RECINTO) REFERENCES ESPECTACULOS(COD_RECINTO) ON UPDATE CASCADE ON DELETE CASCADE
);



CREATE TABLE ZONAS_RECINTOS (

    COD_RECINTO INT,
    ZONA VARCHAR(255) NOT NULL,
    CAPACIDAD INT NOT NULL,
		
        PRIMARY KEY (COD_RECINTO, ZONA),
		CONSTRAINT FK_COD_RECINTO_ZONAS_RECINTOS FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ASIENTOS (
    COD_RECINTO INT,
    ZONA VARCHAR(255),
    FILA VARCHAR(10),
    NUMERO INT,
    PRIMARY KEY (COD_RECINTO, ZONA, FILA, NUMERO),
    CONSTRAINT FK_COD_RECINTO_ASIENTOS FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE REPRESENTACIONES (

    COD_ESPECTACULO INT,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    
		PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA), #METO FECHA Y HORA TB COMO PK POR EL TEMA DE REPRESENTAR DE MANERA UNICA CADA REPRESENTACION DE UN ESPECTACULO
		CONSTRAINT FK_COD_ESPECTACULO_REPRESENTACIONES FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO) ON UPDATE CASCADE ON DELETE CASCADE
);

