#ALUMNO: JONATAN TAJADA RICO

#DROP DATABASE IF EXISTS empleadosEmpresaOrduña;

CREATE DATABASE IF NOT EXISTS empleadosEmpresaOrduña COLLATE utf8mb4_spanish2_ci;
USE empleadosEmpresaOrduña;

CREATE TABLE EMPLEADOS (

    DNI INT PRIMARY KEY,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIR1 VARCHAR(20),
    DIR2 VARCHAR(20),
    CIUDAD VARCHAR(25),
    SEXO ENUM('H', 'M'),
    FECHA_NAC DATE
);

CREATE TABLE DEPARTAMENTOS (

    DPTO_COD INT PRIMARY KEY,
    NOMBRE_DPTO VARCHAR(30) NOT NULL UNIQUE,
    DPTO_PADRE INT,
    PRESUPUESTO INT NOT NULL,
    
		CONSTRAINT FK_DPTO_PADRE FOREIGN KEY (DPTO_PADRE) REFERENCES DEPARTAMENTOS(DPTO_COD) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ESTUDIOS (

    EMPLEADO_DNI INT,
    UNIVERSIDAD INT,
    AÑO YEAR,
    GRADO VARCHAR(3),
    ESPECIALIDAD VARCHAR(20),
    
		PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD),
		CONSTRAINT FK_EMPLEADO_DNI FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE TRABAJOS (

    TRABAJO_COD INT PRIMARY KEY,
    NOMBRE_TRAB VARCHAR(20) NOT NULL UNIQUE,
    SALARIO_MIN FLOAT NOT NULL,
    SALARIO_MAX FLOAT NOT NULL
);


CREATE TABLE UNIVERSIDADES (

    NOMBRE_UNIV INT NOT NULL,
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5)
);


CREATE TABLE HISTORIAL_LABORAL (

    EMPLEADO_DNI INT,
    TRABAJO_COD INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD INT,
    SUPERVISOR_DNI INT,
    SALARIO FLOAT NOT NULL,
    
		PRIMARY KEY (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
		CONSTRAINT FK_EMPLEADO_DNI_HISTORIAL FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
		CONSTRAINT FK_SUPERVISOR_DNI FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI),
		CONSTRAINT FK_TRABAJO_COD FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS(TRABAJO_COD)
);